# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\"\"\n\x0c\x45ventRequest\x12\x12\n\nevent_data\x18\x01 \x01(\t\")\n\rEventResponse\x12\x18\n\x10response_message\x18\x01 \x01(\t2T\n\x0eSimulationData\x12\x42\n\tSendEvent\x12\x18.simulation.EventRequest\x1a\x19.simulation.EventResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTREQUEST']._serialized_start=32
  _globals['_EVENTREQUEST']._serialized_end=66
  _globals['_EVENTRESPONSE']._serialized_start=68
  _globals['_EVENTRESPONSE']._serialized_end=109
  _globals['_SIMULATIONDATA']._serialized_start=111
  _globals['_SIMULATIONDATA']._serialized_end=195
# @@protoc_insertion_point(module_scope)
